### 최소제곱법에 대한 넘파이로 행렬식 만들기!

- 공부시간 3, 4, 5, 6
- 성적 2.5, 3.0, 3.5, 4.3

- 공부시간이 늘수록, 성적도 어느정도 늘어난다.

In [1]:
import numpy as np

In [2]:
np1 = ((3**2)+(4**2)+(5**2)+(6**2))
np2 = (3+4+5+6)
np3 = 4

In [3]:
np1

86

In [4]:
np2

18

In [5]:
X=np.array([[np1, np2],[np3,np2]])

In [6]:
X

array([[86, 18],
       [ 4, 18]])

In [7]:
ynp1=((3*2.5)+(4*3)+(5*3.5)+(6*4.3))
ynp2=(2.5+3.0+3.5+4.3)

In [8]:
ynp1

62.8

In [9]:
ynp2

13.3

In [10]:
Y= np.array([ynp1, ynp2]).reshape(2,1)

In [11]:
Y

array([[62.8],
       [13.3]])

In [12]:
X1=np.linalg.inv(X) 

In [13]:
X1

array([[ 0.01219512, -0.01219512],
       [-0.00271003,  0.05826558]])

In [14]:
np.dot(X1,Y)

array([[0.60365854],
       [0.60474255]])

In [15]:
0.60365854*8 + 0.60474255

5.43401087

## 선형회귀

- 분석적인면에서 선형회귀를 왜 사용하는지? 
- OLS 패키지 가지고 진행 stats model에서 가지고 오는 회귀분석식
- sklearn 회귀분석
- np 직접 만들 수도 있다.


### 1. 데이터에 대한 이해와 관계 등을 알고 통계치를 확인하기 위해서!
- OLS 쪽에서 가지고 오는 회귀분석식을 보면
- 독립변수와 종속변수 그리고 그외 변수들의 관계를 잘 나타내는 지표로 보여준다.
- 그 지표를 기본적으로 해석하면서 데이터들의 관계를 이해하기 쉽다.
- 통계분석-> 통계치에 대한 값들을 정리하면서 변수들간의 관계를 이해할 수 있다.


### 2. 예측도 가능하다
- 회귀분석을 통해 예측도 가능하다.
- 선형적인 한계 존재한다.
- 선형에 대한 가정들이 다 존재하기 때문에 예측에 대한 정확도가 좋긴 어려울 수 있다.

### 3. 인과관계 증명 
- 인과관계 분석하려고 회귀분석도 활용 되어진다.


### 선형적인 관계의 데이터가 아닌 경우는 -> 비선형으로 생각을하고 
- 다항회귀 등의 방법을 문제를 해결하게 된다.

- 컬럼 설명서
- longitude : 경도
- latitude : 위도
- housing_median_age : 주택 나이(중앙값)
- total_rooms : 전체 방 수
- total_bedrooms : 전체 침실 수
- population : 인구 수
- households : 세대 수
- median_income : 소득(중앙값)
- median_house_value : 주택 가치(중앙값)
- ocean_proximity : 바다 근접도

In [16]:
import sklearn
import pandas as pd
from statsmodels.formula.api import ols
import statsmodels.api as sm
from sklearn import datasets

In [17]:
# 캘리포니아 주택가격
calhouse = sklearn.datasets.fetch_california_housing()
dfx = pd.DataFrame(calhouse.data, columns = calhouse.feature_names)
dfy = pd.DataFrame(calhouse.target, columns=['y'])
df = pd.concat([dfx, dfy],axis=1)

In [18]:
df_sp1 = df[['MedInc','y']]

In [19]:
df_sp1

MedInc      y
0      8.3252  4.526
1      8.3014  3.585
2      7.2574  3.521
3      5.6431  3.413
4      3.8462  3.422
...       ...    ...
20635  1.5603  0.781
20636  2.5568  0.771
20637  1.7000  0.923
20638  1.8672  0.847
20639  2.3886  0.894

[20640 rows x 2 columns]

In [20]:
#stats 모델을 이용해서 데이터의 관계 등을 확인해 보자!

model1=sm.OLS.from_formula('y~MedInc',data=df_sp1)
model1_res=model1.fit()

In [21]:
model1_res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.473
Model:                            OLS   Adj. R-squared:                  0.473
Method:                 Least Squares   F-statistic:                 1.856e+04
Date:                Sat, 25 Nov 2023   Prob (F-statistic):               0.00
Time:                        22:34:10   Log-Likelihood:                -25623.
No. Observations:               20640   AIC:                         5.125e+04
Df Residuals:                   20638   BIC:                         5.127e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4509      0.013     34.082      0.000       0.425       0.477
MedInc         0.4179      0.003    136.223      0.000       0.412       0.424
==============================================================================
Omnibus:                     4245.795   Durbin-Watson:                   0.655
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9273.446
Skew:                           1.191   Prob(JB):                         0.00
Kurtosis:                       5.260   Cond. No.                         10.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

- R-squared : 결정계수, 회귀식이 얼마나 설명력이 있는지 확인하는 지표 1이 가낭 좋은 성능
- Adj. R-squared: 조정된 결정계수, 독립변수 여러 개 잇으면 그 중에 조정해서 가장 좋은 값을 만들어 주는 것
- F-statistic: F통계량 회귀식 적절한지 보는 것 0 가가우면 적절하다고 보는 지표 
- Prob (F-statistic): 유의미한지 0.05 이하인 경우는 변수기리 매우 관련있다고 본다
- AIC: 모델 평가 지표 수치 낮을수록 좋은 수치
- BIC:모델 평가하는데 패널티 부여하고 수치가 낮으면 좋은 것

- coef : 회귀계수값
- std err : 계수 추정치에 대한 표준오차 작을수록 좋다
- t t테스트 값들
- P>|t|	: 독립변수가 유의한지를 보는 유의확률 0.05보다 작아야 유의미함

- Omnibus: 비대칭, 첨도 등을 결합해서 정규성 테스트, 값이 크면 클수록 정규분포 가까운 것 
- Prob(Omnibus): 같은 유의확률
- Skew : 왜도
- Kurtosis : 첨도
- Durbin-Watson: 잔차 독립성 여부 판단 1.5~2.5사이일 때 잔차 독립적이다 판단하고, 0이나 4이상등은 자기상관이 있다. 
- Jarque-Bera (JB): 자크베라 검정 정규준포 데이터 사용했다는 것에 대한 내용이 검정값 크면 클수록 정규분포 
- Cond. No.	다중공선성 : 독립변수간의 상관관계 보는 것 10이상이면 다중공선성 있다고 판단하고 진행하는 것 